# Generated by Django 5.1 on 2024-11-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_expense_created_at_expense_user_alter_expense_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reason',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
